#server:
#  port: 8085
#spring:
#  application:
#    name: CONFIGSERVER
#    
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/shweta0027/micro-config-server.git
#          clone-on-start: true 
